title: "China Medical Tour"
description: "World-class medical care combined with deep cultural experiences in China."
baseurl: "/chinamedicaltour" # Project page on GitHub Pages
url: "https://chinamedicaltour.org"
theme: jekyll-theme-cayman # Optional, but good to have a default fallback, though we are using custom HTML
plugins:
  - jekyll-seo-tag
